### ISSUE TITLE
Suggestion to try

### ISSUE THREAD

**Issue by stevejroberts** [jbachelor/DevAuthIdentitiesWithAwsCognitoInXamForms#1]
@jbachelor,  Nicki and I have not gotten this to work fully in the time we have had available so far this week but I thought I'd see if this approach we are currently trying might help. The errors I'm getting currently might be down to my faked-up custom sso provider - since you have a working one, I figured it was worth a go,

On [this page](https://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html), in the Xamarin section, there is mention that you should derive a class from CognitoAWSCredentials and override the RefreshIdentityAsync method:

```
protected override async Task<IdentityState> RefreshIdentityAsync()
    {
        IdentityState state = null;
        //get your identity and set the state
        return state;
    }
```

Two options spring to mind:

1. Derive your AwsCognitoService from CognitoAWSCredentials and add the override. In the override body place your current code from LoginToAwsWithDeveloperAuthenticatedSsoUserAsync (you'll obviously need to get your sso user instance handed in on construction or via a property). At the end of the code, instead of caching the Cognito response etc, form up a new IdentityState instance from the data in the response:

```
return new IdentityState(response.IdentityId, DeveloperProviderName, response.Token, false);
```

I'm not sure on how the final 'fromCache' flag is used yet so have just been passing false.

2. Add a new class derived from CognitoAWSCredentials and call your existing AwsCognitoService.LoginToAwsWithDeveloperAuthenticatedSsoUserAsync  from inside the override, returning data to satisfy the IdentityState constructor or simply hand one back.

I tried (1) earlier and the override was called at the time the SDK's S3 client instance needed to obtain AWS credentials (I handed the derived CognitoAWSCredentials class to the S3 client constructor). Your code ran successfully to get an openID token but an error occurred later - 'Please provide a valid public provider' - as I noted earlier, this may be down to my hacked-up custom sso implementation which is trying to fake it with a user pool and user auth outside this flow. As the tokens are opaque who knows what data is encoded in them about the provider that might lead to this error :-)

We're curious to hear what behavior you get if you try this approach (assuming you haven't already).

**Comment by jbachelor** [comment]
Thank you SO much, @steveataws! I am extremely grateful for your and Nicki's help!

Interesting about deriving the CognitoService from CognitoAWSCredentials. I had seen that in the documentation, and that's actually what I tried first. While the code seemed to work similarly to the current solution, I got an exception every time I constructed the CognitoService coming out of the call to the base constructor for CognitoAWSCredentials. Regardless, the code carried on and created identities in my Identity Pool, but I was concerned about the exception. 

I had thrown a breakpoint in the RefreshIdentityAsync override, and while it never was hit during my experiments, I haven't actually tried to access any other aws services with these Cognito Identity credentials yet, and from what you were saying, it sounds like that won't happen until I do so.

I'll play around with making the CognitoService derive from CognitoAWSCredentials some more, and I'm going to basically try to make your 'option 1' plan above work. I'll report back on how it goes.

Again, thank you so much for your time and help!

**Comment by jbachelor** [comment]
No luck so far with my first try on implementing step 4, "GetCredentialsForIdentity" found [here](https://docs.aws.amazon.com/cognito/latest/developerguide/authentication-flow.html).

I threw the first attempt in a branch called, [*"getCredentialsTake1"*](https://github.com/jbachelor/DevAuthIdentitiesWithAwsCognitoInXamForms/tree/getCredentialsTake1).

I wind up with a **InvalidParameterException**, and a message of, **"Please provide a valid public provider"** on line 73 of the AmazonCognitoService class.

I'll try making the AmazonCognitoService inherit from CognitoAWSCredentials and see how that goes next.

**Comment by jbachelor** [comment]
Hi @steveataws & @kneekey23 - I've just started a new branch, [inheritCAC1](https://github.com/jbachelor/DevAuthIdentitiesWithAwsCognitoInXamForms/tree/inheritCAC1). Trying to implement @steveataws's 'option 1' from his initial comment.

Two early problems arose:
* The constructor throws a *System.InvalidOperationException*, with a message of, *"The app.config/web.config files for the application did not contain region information"*, even though I provide the region in the constructor. Do you know what I'm doing wrong here?
* The [AWS documentation Steve mentioned](https://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html) has the override of RefreshIdentityAsync as *protected*. When pasting that code in my AwsCognitoService class that now inherits from CognitoAWSCredentials, I get a build error. It seems this method must be public. If so, it might be worth letting someone on the documentation team know about this.

Logging in and establishing a Cognito identity of some sort (unauthenticate?) still seems to work the same, however, when attempting to execute my AWS Lamba function, I get an *InvalidParameterException:  Please provide a valid public provider.*

Any ideas on what I've got wrong here?

Thanks for your help!

**Comment by jbachelor** [comment]
The *inheritCAC1* branch has been merged to master.

I now have a first working version, I believe (see [this tag](https://github.com/jbachelor/DevAuthIdentitiesWithAwsCognitoInXamForms/releases/tag/FirstWorkingVersion)). I still get the *System.InvalidOperationException* with a message of *"The app.config/web.config files for the application did not contain region information"* when the AwsCognitoService is instantiated and the base constructor for *CognitoAWSCredentials* is called.

However, the code seems to successfully create a user in my Cognito identity pool, then it gets credentials for that user using the Amazon provider string of *cognito-identity.amazonaws.com* as a key to get to the Cognito-provided identity token in the Logins collection of the credential request. It seems to be crucial that I *not* include the provider name and user id that I used to create the Developer Authenticated Identity, which is certainly confusing to me, but AWS throws an exception when I include that.

**Comment by sunchunqiang** [comment]
Hi @jbachelor 
With your current code, when is the System.InvalidOperationException thrown? Is it thrown before or after the login button is clicked? Can you provide the StackTrace of the exception?

**Comment by jbachelor** [comment]
Hi @sunchunqiang! Thanks so much for joining in!

The System.InvalidOperationException is thrown long before you tap the 'Log In' button. It is thrown when the constructor of the AwsCognitoService class is called. Specifically, I believe it is the call to the base constructor (AwsCognitoService inherits from CognitoAWSCredentials, as suggested in the AWS documentation and by @steveataws).

This constructor is called upon instantiation of the MainPageViewModel, since the MainPageViewModel is asking for an IAwsCognitoService in its constructor.

Here is the stack trace I get in the exception:

> System.InvalidOperationException: The app.config/web.config files for the application did not contain region information
>   at Amazon.Runtime.AppConfigAWSRegion..ctor () [0x0005c] in <64edd21dc28f491a8814f2cd31c3d774>:0
>   at Amazon.Runtime.FallbackRegionFactory+<>c.<Reset>b__11_1 () [0x00000] in <64edd21dc28f491a8814f2cd31c3d774>:0
>   at Amazon.Runtime.FallbackRegionFactory.GetRegionEndpoint (System.Boolean includeInstanceMetadata) [0x0004e] in <64edd21dc28f491a8814f2cd31c3d774>:0

And here is the much longer stacktrace that Visual Studio shows at the point the exception is thrown:

> Amazon.Runtime.AppConfigAWSRegion..ctor() in 
> Amazon.Runtime.FallbackRegionFactory.<>c.<Reset>b__11_1() in 
> Amazon.Runtime.FallbackRegionFactory.GetRegionEndpoint(bool includeInstanceMetadata) in 
> Amazon.SecurityToken.AmazonSecurityTokenServiceConfig..ctor() in 
> Amazon.SecurityToken.AmazonSecurityTokenServiceClient..ctor(Amazon.Runtime.AnonymousAWSCredentials credentials, Amazon.RegionEndpoint region) in 
> Amazon.CognitoIdentity.CognitoAWSCredentials..ctor(string accountId, string identityPoolId, string unAuthRoleArn, string authRoleArn, Amazon.RegionEndpoint region) in 
> SimpleAwsSample.Services.AwsCognitoService..ctor(Prism.Events.EventAggregator eventAggregator) in /Users/Shared/src/AwsCognitoSSOSample/SimpleAwsSample/SimpleAwsSample/Services/AwsCognitoService.cs:27
> System.Reflection.MonoCMethod.InternalInvoke() in 
> System.Reflection.MonoCMethod.InternalInvoke(object obj, object[] parameters, bool wrapExceptions) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/MonoMethod.cs:667
> System.Reflection.MonoCMethod.DoInvoke(object obj, System.Reflection.BindingFlags invokeAttr, System.DefaultBinder binder, object[] parameters, System.Globalization.CultureInfo culture) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/MonoMethod.cs:657
> System.Linq.Expressions.Interpreter.NewInstruction.Run(System.Linq.Expressions.Interpreter.InterpretedFrame frame) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/NewInstruction.cs:35
> System.Linq.Expressions.Interpreter.Interpreter.Run(System.Linq.Expressions.Interpreter.InterpretedFrame frame) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/Interpreter.cs:63
> System.Linq.Expressions.Interpreter.LightLambda.Run0<object>() in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/LightLambda.Generated.cs:22
> DryIoc.Scope.TryGetOrAdd(ImTools.ImMap<object> items, int id, DryIoc.CreateScopedValue createValue, int disposalOrder) in 
> DryIoc.Scope.GetOrAdd(int id, DryIoc.CreateScopedValue createValue, int disposalOrder) in 
> System.Reflection.MonoMethod.InternalInvoke() in 
> System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Run(System.Linq.Expressions.Interpreter.InterpretedFrame frame) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/CallInstruction.cs:348
> System.Linq.Expressions.Interpreter.Interpreter.Run(System.Linq.Expressions.Interpreter.InterpretedFrame frame) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/Interpreter.cs:63
> System.Linq.Expressions.Interpreter.LightLambda.Run1<Xamarin.Forms.Page, object>(SimpleAwsSample.Views.MainPage arg0) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/LightLambda.Generated.cs:53
> Prism.DryIoc.DryIocContainerExtension.ResolveViewModelForView(SimpleAwsSample.Views.MainPage view, System.RuntimeType viewModelType) in D:/a/1/s/Source/Xamarin/Prism.DryIoc.Forms/DryIocContainerExtension.cs:58
> Prism.PrismApplicationBase.<ConfigureViewModelLocator>b__23_0(SimpleAwsSample.Views.MainPage view, System.RuntimeType type) in D:/a/1/s/Source/Xamarin/Prism.Forms/PrismApplicationBase.cs:94
> Prism.Mvvm.ViewModelLocationProvider.AutoWireViewModelChanged(SimpleAwsSample.Views.MainPage view, System.Action<object,object> setDataContextCallback) in D:/a/1/s/Source/Prism/Mvvm/ViewModelLocationProvider.cs:107
> Prism.Mvvm.ViewModelLocator.OnAutowireViewModelChanged(SimpleAwsSample.Views.MainPage bindable, object oldValue, bool newValue) in D:/a/1/s/Source/Xamarin/Prism.Forms/Mvvm/ViewModelLocator.cs:60
> Xamarin.Forms.BindableObject.SetValueActual(Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject.BindablePropertyContext context, bool value, bool currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, bool silent) in D:/a/1/s/Xamarin.Forms.Core/BindableObject.cs:625
> Xamarin.Forms.BindableObject.SetValueCore(Xamarin.Forms.BindableProperty property, bool value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject.SetValuePrivateFlags privateAttributes) in D:/a/1/s/Xamarin.Forms.Core/BindableObject.cs:417
> Xamarin.Forms.BindableObject.SetValue(Xamarin.Forms.BindableProperty property, bool value, bool fromStyle, bool checkAccess) in D:/a/1/s/Xamarin.Forms.Core/BindableObject.cs:573
> Xamarin.Forms.BindableObject.SetValue(Xamarin.Forms.BindableProperty property, bool value) in D:/a/1/s/Xamarin.Forms.Core/BindableObject.cs:99
> Prism.Mvvm.ViewModelLocator.SetAutowireViewModel(SimpleAwsSample.Views.MainPage bindable, bool? value) in D:/a/1/s/Source/Xamarin/Prism.Forms/Mvvm/ViewModelLocator.cs:43
> Prism.Common.PageUtilities.SetAutowireViewModelOnPage(SimpleAwsSample.Views.MainPage page) in D:/a/1/s/Source/Xamarin/Prism.Forms/Common/PageUtilities.cs:265
> Prism.Navigation.PageNavigationService.CreatePageFromSegment(string segment) in D:/a/1/s/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs:750
> Prism.Navigation.PageNavigationService.UseReverseNavigation() in D:/a/1/s/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs:955
> System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Prism.Navigation.PageNavigationService.<UseReverseNavigation>d__57>(Prism.Navigation.PageNavigationService stateMachine) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316
> Prism.Navigation.PageNavigationService.UseReverseNavigation(Xamarin.Forms.NavigationPage currentPage, string nextSegment, System.Collections.Generic.Queue<string> segments, Prism.Navigation.INavigationParameters parameters, bool? useModalNavigation, bool animated) in 
> Prism.Navigation.PageNavigationService.ProcessNavigationForNavigationPage() in D:/a/1/s/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs:508
> System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Prism.Navigation.PageNavigationService.<ProcessNavigationForNavigationPage>d__39>(Prism.Navigation.PageNavigationService stateMachine) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316
> Prism.Navigation.PageNavigationService.ProcessNavigationForNavigationPage(Xamarin.Forms.NavigationPage currentPage, string nextSegment, System.Collections.Generic.Queue<string> segments, Prism.Navigation.INavigationParameters parameters, bool? useModalNavigation, bool animated) in 
> Prism.Navigation.PageNavigationService.ProcessNavigation() in D:/a/1/s/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs:333
> System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Prism.Navigation.PageNavigationService.<ProcessNavigation>d__30>(Prism.Navigation.PageNavigationService stateMachine) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316
> Prism.Navigation.PageNavigationService.ProcessNavigation(Xamarin.Forms.NavigationPage currentPage, System.Collections.Generic.Queue<string> segments, Prism.Navigation.INavigationParameters parameters, bool? useModalNavigation, bool animated) in 
> Prism.Navigation.PageNavigationService.ProcessNavigationForRootPage() in D:/a/1/s/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs:428
> System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Prism.Navigation.PageNavigationService.<ProcessNavigationForRootPage>d__37>(Prism.Navigation.PageNavigationService stateMachine) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316
> Prism.Navigation.PageNavigationService.ProcessNavigationForRootPage(string nextSegment, System.Collections.Generic.Queue<string> segments, Prism.Navigation.INavigationParameters parameters, bool? useModalNavigation, bool animated) in 
> Prism.Navigation.PageNavigationService.ProcessNavigation() in D:/a/1/s/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs:323
> System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Prism.Navigation.PageNavigationService.<ProcessNavigation>d__30>(Prism.Navigation.PageNavigationService stateMachine) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316
> Prism.Navigation.PageNavigationService.ProcessNavigation(Xamarin.Forms.Page currentPage, System.Collections.Generic.Queue<string> segments, Prism.Navigation.INavigationParameters parameters, bool? useModalNavigation, bool animated) in 
> Prism.Navigation.PageNavigationService.NavigateInternal() in D:/a/1/s/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs:281
> System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Prism.Navigation.INavigationResult>.Start<Prism.Navigation.PageNavigationService.<NavigateInternal>d__28>(Prism.Navigation.PageNavigationService stateMachine) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
> Prism.Navigation.PageNavigationService.NavigateInternal(System.Uri uri, Prism.Navigation.INavigationParameters parameters, bool? useModalNavigation, bool animated) in 
> Prism.Navigation.PageNavigationService.NavigateInternal(string name, Prism.Navigation.INavigationParameters parameters, bool? useModalNavigation, bool animated) in D:/a/1/s/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs:218
> Prism.Navigation.PageNavigationService.NavigateAsync(string name, Prism.Navigation.INavigationParameters parameters) in D:/a/1/s/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs:203
> Prism.Navigation.PageNavigationService.NavigateAsync(string name) in D:/a/1/s/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs:193
> SimpleAwsSample.App.OnInitialized() in /Users/Shared/src/AwsCognitoSSOSample/SimpleAwsSample/SimpleAwsSample/App.xaml.cs:27
> System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start<SimpleAwsSample.App.<OnInitialized>d__2>(SimpleAwsSample.App stateMachine) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:84
> SimpleAwsSample.App.OnInitialized() in 
> Prism.PrismApplicationBase.InitializeInternal() in D:/a/1/s/Source/Xamarin/Prism.Forms/PrismApplicationBase.cs:84
> Prism.PrismApplicationBase..ctor(SimpleAwsSample.iOS.iOSInitializer platformInitializer, bool setFormsDependencyResolver) in D:/a/1/s/Source/Xamarin/Prism.Forms/PrismApplicationBase.cs:74
> Prism.PrismApplicationBase..ctor(SimpleAwsSample.iOS.iOSInitializer platformInitializer) in D:/a/1/s/Source/Xamarin/Prism.Forms/PrismApplicationBase.cs:56
> Prism.DryIoc.PrismApplication..ctor(SimpleAwsSample.iOS.iOSInitializer platformInitializer) in D:/a/1/s/Source/Xamarin/Prism.DryIoc.Forms/PrismApplication.cs:31
> SimpleAwsSample.App..ctor(SimpleAwsSample.iOS.iOSInitializer initializer) in /Users/Shared/src/AwsCognitoSSOSample/SimpleAwsSample/SimpleAwsSample/App.xaml.cs:21
> SimpleAwsSample.iOS.AppDelegate.FinishedLaunching(UIKit.UIApplication app, Foundation.NSDictionary options) in /Users/Shared/src/AwsCognitoSSOSample/SimpleAwsSample/SimpleAwsSample.iOS/AppDelegate.cs:25
> UIKit.UIApplication.UIApplicationMain() in 
> UIKit.UIApplication.Main(string[] args, System.IntPtr principal, System.IntPtr delegate) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/UIKit/UIApplication.cs:79
> UIKit.UIApplication.Main(string[] args, string principalClassName, string delegateClassName) in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/UIKit/UIApplication.cs:63
> SimpleAwsSample.iOS.Application.Main(string[] args) in /Users/Shared/src/AwsCognitoSSOSample/SimpleAwsSample/SimpleAwsSample.iOS/Main.cs:17

**Comment by sunchunqiang** [comment]
Hi @jbachelor 

Thanks for your information. I found the issue from the StackTrace.  FallbackRegionFactory.GetRegionEndpoint(false) in below code will try to get the region from configure file. At the moment, if AWSConfigs.RegionEndpoint is not set, it will throw the exception. 
This is a bug, as Xamarin sdk should not read region information from configure file. 

https://github.com/aws/aws-sdk-net/blob/11e2a5a7ca0a0806767247af2ed647a0e41a2e06/sdk/src/Services/SecurityToken/Generated/AmazonSecurityTokenServiceConfig.cs
public AmazonSecurityTokenServiceConfig()
{
this.AuthenticationServiceName = "sts";
var region = FallbackRegionFactory.GetRegionEndpoint(false);
this.RegionEndpoint = region ?? RegionEndpoint.USEast1;
}

To eliminate the exception, you can call below code before constructing AwsCognitoService 
or you can ignore it as it is a fake exception, it should not be thrown.

AWSConfigs.RegionEndpoint = AwsConstants.AppRegionEndpoint;

**Comment by nikhil-dabhade** [comment]
Thank you for the help on this issue @sunchunqiang 
@jbachelor Looking at the thread it seems that you have been able to get it working but the exception was the piece that was bothersome which is completely understandable and should be fixed. Is that correct? If yes, given input from Sun above, are you ok with using this workaround for now until we figure out long term solution for this item?

**Comment by jbachelor** [comment]
Thanks so much, @sunchunqiang! I added your suggested line of code in App.xaml.cs in order to set the region endpoint prior to instantiation of the MainPageViewModel (which in turn triggers the instantiation of the AwsCognitoService).

Much thanks also to @nikhil-dabhade... Yes, this is a perfectly fine work-around!

Thanks so much for all your help, everyone... I *greatly* appreciate your time and knowledge!

**Comment by nikhil-dabhade** [comment]
Glad we could help.

**Comment by sunchunqiang** [comment]
Hi @jbachelor
I am going to resolve the issue, but I still don't understand how you get the exception System.InvalidOperationException. The exception is really thrown, but it's already catch in aws sdk code. I can see the exception when I set a breakpoint at the location where the exception is thrown, but I cannot catch the exception from client code.
